version: '3'

services:
  api:
    image: lbdev77/egi-api:0.01
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/dev/egi-api
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: egi-db
    tty: true
    env_file: .env
    environment:
      - POSTGRES_DB=$PSG_DB
      - POSTGRES_USER=$PSG_USER
      - POSTGRES_PASSWORD=$PSG_PASSWORD
    volumes:
      - egi-pgdata:/var/lib/postgresql/data

volumes:
  egi-pgdata:
    external: true