version: '3'

services:
  api:
    build: .
    container_name: egi_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/egi/api
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:lts
    container_name: egi_db
    tty: true
    env_file: .env
    environment:
      - POSTGRES_DB=$PSG_DB
      - POSTGRES_USER=$PSG_USER
      - POSTGRES_PASSWORD=$PSG_PASSWORD
    volumes:
      - egi-pgdata:/var/lib/postgresql/data

volumes:
  egi-pgdata:
    external: true