# Generated by Django 4.1 on 2023-04-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=4)),
                ('postal_code', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('category', models.CharField(choices=[('00', 'Geral'), ('01', 'Esportes'), ('02', 'Cultura')], default='Geral', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('ticket', models.CharField(blank=True, max_length=8, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('star', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=40, null=True)),
                ('video_url', models.CharField(blank=True, max_length=40, null=True)),
                ('addrees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.addrees')),
            ],
        ),
    ]
